version: '3'
services:
  bot:
    build: .
    ports:
      - '3030:3030'
    depends_on:
      - redis
      - mongo
    restart: unless-stopped
    env_file:
      - .env

  prometheus:
    image: ./docker/prometheus
    ports:
      - '9090:9090'
    restart: unless-stopped

  grafana:
    image: ./docker/grafana
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    restart: unless-stopped

  redis-exporter:
    image: oliver006/redis_exporter:alpine
    environment:
      REDIS_ADDR: 'redis://redis:6379'
    restart: unless-stopped

  mongo:
    image: mongo
    restart: unless-stopped
