version: '3'
services:
  bot:
    build: .
    ports:
      - '3030:3030'
    restart: always
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    restart: always
  grafana:
    image: grafana/grafana
    depends_on: prometheus
    ports:
      - '3000:3000'
    restart: always
