version: '3.7'
services:
  bot:
    build: .
    ports:
      - '3030:3030'
    depends_on:
      - redis
      - mongo
    restart: unless-stopped
    env_file:
      - .env

  prometheus:
    build: ./docker/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus-storage:/prometheus
    restart: unless-stopped

  grafana:
    build: ./docker/grafana
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-piechart-panel,flant-statusmap-panel,grafana-github-datasource'
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    restart: unless-stopped

  redis-exporter:
    image: oliver006/redis_exporter:alpine
    ports:
      - '9121:9121'
    environment:
      REDIS_ADDR: 'redis://redis:6379'
    restart: unless-stopped

  mongo:
    image: mongo
    volumes:
      - mongo-storage:/data/db
    restart: unless-stopped

  mongo-exporter:
    image: noenv/mongo-exporter
    command: --web.listen-address=:9123 --mongodb.uri=mongodb://mongo:27017
    depends_on:
      - mongo
    ports:
      - '9123:9123'
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:8.2.3
    ports:
      - '9200:9200'
    environment:
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      discovery.type: single-node
    volumes:
      - elastic-storage:/usr/share/elasticsearch/data
    restart: unless-stopped

  kibana:
    image: kibana:8.2.3
    depends_on:
      - elasticsearch
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    restart: unless-stopped

volumes:
  prometheus-storage:
  grafana-storage:
  mongo-storage:
  elastic-storage:
