version: '3'
services:
  bot:
    build: .
    ports:
      - '3030:3030'
    depends_on:
      - redis
      - mongo
    restart: always
    env_file:
      - .env
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    restart: always
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    restart: always
  redis:
    image: redis
    restart: always
  mongo:
    image: mongo
    restart: always
