version: '3'
services:
  bot:
    build: .
    ports:
      - '3030:3030'
    depends_on:
      - redis
      - mongo
    restart: unless-stopped
    env_file:
      - .env

  prometheus:
    build: ./docker/prometheus
    ports:
      - '9090:9090'
    restart: unless-stopped

  grafana:
    build: ./docker/grafana
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    restart: unless-stopped

  redis-exporter:
    image: oliver006/redis_exporter:alpine
    ports:
      - '9121:9121'
    environment:
      REDIS_ADDR: 'redis://redis:6379'
    restart: unless-stopped

  mongo:
    image: mongo
    restart: unless-stopped

  mongo-exporter:
    image: noenv/mongo-exporter
    command: --web.listen-address=:9123 --mongodb.uri=mongodb://mongo:27017
    depends_on:
      - mongo
    ports:
      - '9123:9123'
    restart: unless-stopped
