name: Bug Report
description: File a bug report here
title: "bug: "
labels: [bug]
body:
  - type: checkboxes
    id: new-bug
    attributes:
      label: Is there an existing issue for this?
      description: |
        Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: |
        Describe the issue in as much detail as possible.
      placeholder: |
        Tell us what bug you encountered and what should have happened
    validations:
      required: true
  - type: textarea
    id: reproducible
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Write '...'
        2. Click on '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: |
        Tell us what you expected to happen
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: |
        Drag and drop your screenshots here
  - type: dropdown
    id: priority
    attributes:
      label: Priority this issue should have
      description: |
        Choose the priority of the issue.
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true
      