name: Feature Request
description: Suggest an idea for this project
title: "request: "
labels: ['feature request']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: checkboxes
    id: new-feature
    attributes:
      label: Is there an existing issue or pull request for this?
      description: |
        Please search to see if an issue or pull request already exists for the feature you are suggesting.
      options:
        - label: I have searched the existing issues and pull requests
          required: true
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: |
        Describe the feature you are suggesting in as much detail as possible.
      placeholder: |
        Tell us what you would like to see and why
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
        label: Desired solution
        description: |
          Describe the solution you would like to see in as much detail as possible.
        placeholder: |
          Tell us how you would like to see this feature implemented
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: |
        Describe any alternative solutions you have considered.
      placeholder: |
        Tell us what alternatives you have considered
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Do you want to share any additional context about this feature request?
      placeholder: |
        Add any other context or screenshots about the feature request here.