import { Snowflake } from 'discord.js';
import { Document, model, ObjectId, Schema } from 'mongoose';

export interface MemberData {
	/**
	 * Id is autogenerated
	 */
	_id: ObjectId;

	/**
	 * The Member Id
	 */
	memberId: Snowflake;

	/**
	 * The guild Id
	 */
	guildId: Snowflake;

	/**
	 * A collection of times spent in vc
	 */
	vcHours?: number[] | null;

	/**
	 * The roles the member has in the guild
	 */
	roles?: Snowflake[] | null;

	/**
	 * Array of mutes in the guild
	 */
	mutes?: string[] | null;

	/**
	 * Array of warns in the guild
	 */
	warns?: string[] | null;
}

export type IMember = Document & MemberData;

const memberSchema = new Schema<IMember>({
	memberId: { type: String, required: true },
	guildId: { type: String, required: true },
	vcHours: { type: [Number], default: null },
	roles: { type: Array, default: [] },
	mutes: { type: Array, default: [] },
	warns: { type: Array, default: [] },
});

export default model('Member', memberSchema);
