name: "PR Automation"
on:
  pull_request_target:
    types: [opened, ready_for_review]
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Automatically assign reviewers
        use: kentaro-m/auto-assign-action@v1.2.1